### ISSUE TITLE
Etiqueta huerfana?

### ISSUE THREAD

**Issue by PucciFernando** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-arilow#4]
Consulto: librería I2C.inc: linea 58
Donde salta la etiqueta errloop?

**Comment by arilow** [comment]
Buen dia profe. Esa etiqueta esta en el main. Esta pensada para usarse en casa de que puede haber cualquier tipo de error. Deberíamos ponerla en otro archivo?

**Comment by PucciFernando** [comment]
En el i2c si hay un error no salten al main. Hagan el loop ahí o respeten por las dudas. O duerman al micro mejor.
